language: node_js
node_js:
- 8.11.3
before_install:
- export TZ=Asia/Taipei
install:
- yarn
script:
- git clone --depth 1 --branch gh-pages https://$GH_TOKEN@github.com/Panepo/Satsuki
  build
- yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  keep-history: true
  local-dir: build
  on:
    branch: master
branches:
  only:
  - master
notifications:
  email: false
env:
  global:
  - secure: XwHhcWfy97ygSlRGfAzKm6tJvffPxfwEs8h+rejjkUGPEyq0j6vqu3i5vOcBUB1JrK0KsqrtYzmjSi+bsTWA4llUJpANE2aV247+5b1glesp5+RQExx3785+fRB6r/1r9uZHjzPNTVqWLPSCb+/UZYqN9O8HvyfP65RpDdoQxSwTCSgL9yGzSs2Eg5sldGKj8zVPLBVnnDDJOjipkVmjgm3MfwZgnNtcrq4GTvTtbDL58uqanXVMWXtRYpBBKKf3m33Yigh7PaogbxYPEYQSHp7fAtC6i0V6spIyebdOBLln9IYlmvZ4MAa/Aq/rqXGBsGPm+GQEeQnu2KJ6Zrr7TARuEpZM4C9o3/utekEEHiA663b1u4Y3BspNhEqCI1FU0FBx04dhHW4B8+Dbttr5tt2ViPhNtBJeFctpKSGesxSy5m25Ze3kz+yd6JiHF0/PCvid/LCREO6PX7oz5WpHHniN8tjXVuOekN5OPm+XGi1Pj4vg9f3eaq04uzpKJB6M9jBSrTT3itUm/Vl+KsZvh7kgVKO4KrXNJoV4FgTSl5x/bx871VXNhdpbNrSwiAifuZ3rBn9MClNfzT6EBnaM4LdxQcfDmnDbS2mGffsvyElZl2EVosERH3H2N6bU8auw0yfXJodkbV8+S+eX/Gd31Vpy9ecIwGVZ4WiMzI/9qbo=
